name: glass_down_v2
description: "Simple app which allows downloading specific APK version of provided apps."
publish_to: "none"
version: 1.5.0-dev3+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  animations: ^2.0.11
  async: ^2.11.0
  cached_network_image: ^3.3.1
  dart_mappable: ^4.2.0
  device_info_plus: ^9.1.2
  dio: ^5.4.1
  dynamic_color: ^1.6.9
  file_picker: ^6.1.1
  flutter:
    sdk: flutter
  flutter_archive: ^6.0.0
  flutter_logs: ^2.1.11
  flutter_markdown: ^0.6.20
  flutter_native_splash: ^2.3.10
  google_fonts: ^6.1.0
  html: ^0.15.4
  internet_connection_checker_plus: ^2.2.0
  intl: ^0.19.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  open_filex: ^4.4.0
  package_info_plus: ^5.0.1
  path: ^1.8.3
  path_provider: ^2.1.2
  permission_handler: ^11.2.0
  shared_preferences: ^2.2.2
  stacked: ^3.4.1+1
  stacked_services: ^1.3.0
  drift: ^2.15.0
  sqlite3_flutter_libs: ^0.5.0
  sqlite3: ^2.4.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mockito: ^5.4.4
  stacked_generator: ^1.5.1
  dart_mappable_builder: ^4.2.0
  isar_generator: ^3.1.0+1
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0
  drift_dev: ^2.15.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/glass_down_2.png"

flutter:
  uses-material-design: true

flutter_native_splash:
  color: "#0490ff"
  image: assets/glass_down_2.png
  android_12:
    image: assets/glass_down_2_icon.png
    color: "#0490ff"
