name: glass_down_v2
description: "Simple app which allows downloading specific APK version of apps from APKMirror."
publish_to: "none"
version: 2.2.2

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  animations: ^2.0.11
  async: ^2.11.0
  cached_network_image: ^3.3.1
  dart_mappable: ^4.2.2
  device_info_plus: ^10.1.0
  dio: ^5.4.3+1
  dynamic_color: ^1.7.0
  file_picker: ^8.0.3
  flutter:
    sdk: flutter
  flutter_archive: ^6.0.3
  flutter_logs: ^2.1.12
  flutter_markdown: ^0.7.1
  flutter_native_splash: ^2.4.0
  google_fonts: ^6.2.1
  html: ^0.15.4
  internet_connection_checker_plus: ^2.4.1
  intl: ^0.19.0
  open_filex: ^4.4.0
  package_info_plus: ^8.0.0
  path: ^1.9.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.3
  stacked: ^3.4.2
  stacked_services: ^1.5.0
  drift: ^2.18.0
  sqlite3_flutter_libs: ^0.5.22
  sqlite3: ^2.4.3
  flutter_svg: ^2.0.10+1
  device_apps: ^2.2.0
  android_system_font:
    git:
      url: https://github.com/re7gog/android_system_font
      ref: master

dev_dependencies:
  build_runner: ^2.4.10
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.4.4
  stacked_generator: ^1.6.0
  dart_mappable_builder: ^4.2.3
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.2.0
  drift_dev: ^2.18.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/glass_down_2.png"

flutter:
  uses-material-design: true
  assets:
    - "assets/icon/glass_down_2.png"
    - "assets/revanced/revanced-logo-shape-dark.svg"
    - "assets/revanced/revanced-logo-shape-light.svg"

flutter_native_splash:
  color: "#0490ff"
  image: assets/glass_down_2.png
  android_12:
    image: assets/glass_down_2_icon.png
    color: "#0490ff"
