# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: GlassDown Dev Release
            
on:
  workflow_dispatch:
    

jobs:
  version:
    name: Create version number
    runs-on: ubuntu-latest
    outputs:
      app-version: ${{ steps.flutter_version.outputs.version_number }}-${{ steps.flutter_version.outputs.build_number }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Flutter Version
        id: flutter_version
        uses: bungabear/flutter_version_read@main

  build:
    name: Create app build
    needs: version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "17"
          cache: 'gradle'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.6"
          channel: 'stable'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Get stacked CLI
        run: dart pub global activate stacked_cli

      - name: Run build_runner
        run: stacked generate

      - name: Start release build
        run: flutter build apk --split-per-abi --target-platform android-arm,android-arm64

      - name: Add version to APK - arm64
        run: mv build/app/outputs/flutter-apk/app-arm64-v8a-release.apk glass_down-arm64-v8a-${{ needs.version.outputs.app-version }}.apk

      - name: Add version to APK - arm32
        run: mv build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk glass_down-armeabi-v7a-${{ needs.version.outputs.app-version }}.apk

      - name: Upload Android Release - arm64-v8a
        uses: actions/upload-artifact@v4
        with:
          name: glass_down-arm64-v8a-${{ needs.version.outputs.app-version }}
          path: glass_down-arm64-v8a-${{ needs.version.outputs.app-version }}.apk

      - name: Upload Android Release - armeabi-v7a
        uses: actions/upload-artifact@v4
        with:
          name: glass_down-armeabi-v7a-${{ needs.version.outputs.app-version }}
          path: glass_down-armeabi-v7a-${{ needs.version.outputs.app-version }}.apk

